### ISSUE TITLE
Work Item is picked and processed multiple times.

### ISSUE THREAD

**Issue by agabuza** [wanlitao/HangfireExtension#3]
Looks like there is some synchronization and/or DB locking issue.
Same Work Item processed multiple times (even when max attempts count set) and then stuck in processing forever. In case of large number of workers it might lead to the situation when same work item is being processed by multiple workers in the same time.
Any idea or similar issues?

**Comment by wanlitao** [comment]
As SQLite DB Locking base on OS file system, there is no reliable way to achieve distributed lock. So best practices is no concurrency, set the workers count to 1 just as follows:

``` cs
new BackgroundJobServer(new BackgroundJobServerOptions { WorkerCount = 1 });
```

**Comment by odinserj** [comment]
I believe the main root of the problem is the dequeue method, where [GET-UPDATE operation](https://github.com/wanlitao/HangfireExtension/blob/master/Hangfire.SQLite/SQLiteJobQueue.cs#L71) is non-atomic, because there is no any transaction. This allows multiple workers to pick up the same background job, leading to multiple executions.

**Comment by NicolasDorier** [comment]
I am hitting this problem as well...

**Comment by darkthread** [comment]
I have a idea to fix this issue. #19

**Comment by firatesmer** [comment]
WorkerCount = 1 worked for me.
